general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# 5分钟 → 锁屏
listener {
    timeout = 300
    on-timeout = hyprlock
}

# 10分钟 → 关闭显示器
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 30分钟 → 强制睡眠（suspend），绝不休眠
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
