music_directory    "/home/jianlongliu/Music"
playlist_directory "/home/jianlongliu/.config/mpd/playlists"
db_file            "/home/jianlongliu/.config/mpd/database"
log_file           "/home/jianlongliu/.config/mpd/log"
pid_file           "/home/jianlongliu/.config/mpd/pid"
state_file         "/home/jianlongliu/.config/mpd/state"
sticker_file       "/home/jianlongliu/.config/mpd/sticker.sql"

auto_update "yes"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

audio_output {
    type    "pipewire"
    name    "PipeWire Sound Server"
}
