# ~/.config/mpd/mpd.conf
# 记得手动创建目录

music_directory    "/home/<username>/Music"
playlist_directory "/home/<username>/.config/mpd/playlists"
db_file            "/home/<username>/.config/mpd/database"
log_file           "/home/<username>/.config/mpd/log"
pid_file           "/home/<username>/.config/mpd/pid"
state_file         "/home/<username>/.config/mpd/state"
sticker_file       "/home/<username>/.config/mpd/sticker.sql"

auto_update "yes"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

audio_output {
    type    "pipewire"
    name    "PipeWire Sound Server"
}
